version: "3.2"
services:
  python:
    build: "./"
    ports:
      - 8008:8008
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:8088/healthcheck || exit 1
      interval: 10s
      timeout: 5s
      retries: 6
